#!/usr/bin/env bash
set -e
module_dir="$(dirname "$(realpath "$(readlink -f "$0")")")"
module_parent=$(dirname "$module_dir")
module_name=$(basename "$module_dir")

if [[ -x "$module_parent/.venv/bin/python" ]]; then
    PYTHON_BIN="$module_parent/.venv/bin/python"
    export VPN_BUNDLE_DEV_MODE=true
elif command -v python3 &>/dev/null; then
    PYTHON_BIN="python3"
else
    PYTHON_BIN="python"
fi

if [[ -e "$module_dir/.dev" ]]; then
    export VPN_BUNDLE_DEV_MODE=true
fi

if [[ $VPN_BUNDLE_DEV_MODE == true ]]; then
    # export VPN_BUNDLE_LOG_SYSLOG=1
    echo " >>>>  Running in Dev Mode | PYTHON_BIN=($PYTHON_BIN) pwd=$(pwd) module_dir=$module_dir exe=$0 args=$*" >&2
fi

if [[ "$*" != *--provider* ]]; then
    provider=$(basename "$0")
    provider="${provider#"nm-"}"
    provider="${provider%"-service"}"
    set -- --provider "$provider" "$@"
fi

cd "$module_parent"
export PYTHONPATH="$module_parent:$PYTHONPATH"
exec "$PYTHON_BIN" -m "$module_name" "$@"
