#!/usr/bin/env bash
set -e
module_dir="$(dirname "$(realpath "$(readlink -f "$0")")")"
module_parent=$(dirname "$module_dir")
module_name=$(basename "$module_dir")

if [[ -x "$module_parent/.venv/bin/python" ]]; then
    PYTHON_BIN="$module_parent/.venv/bin/python"
    echo " >>>>  Detected virtualenv ($PYTHON_BIN) | Running in Dev Mode. pwd=$(pwd) module_dir=$module_dir bin=$0 args=$*" >&2
    # export NM_VPN_LOG_SYSLOG=1
    export NM_VPN_DEV_MODE=true
elif command -v python3 &>/dev/null; then
    PYTHON_BIN="python3"
else
    PYTHON_BIN="python"
fi

if [[ "$*" != *--provider* ]]; then
    provider=$(basename "$0")
    provider="${provider#"nm-"}"
    provider="${provider%"-service"}"
    set -- --provider "$provider" "$@"
fi

cd "$module_parent"
export PYTHONPATH="$module_parent:$PYTHONPATH"
exec "$PYTHON_BIN" -m "$module_name" "$@"
